name: Scheduled jobs

on:
  schedule:
    # Sunday at 20:00 UTC
    - cron: '0 18 * * 0'
    # Mondayâ€“Friday at 15:00 UTC
    - cron: '0 15 * * 1-5'
  workflow_dispatch: # Allow manual run

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run start
        env:
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: bun run start
